version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./API:/app
    networks:
      - my_network

  tts:
    build:
      context: .
      dockerfile: TTS/Dockerfile
    ports:
      - "5003:5003"
    volumes:
      - ./TTS:/app
    networks:
      - my_network

  stt:
    build:
      context: .
      dockerfile: STT/Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./STT:/app
    networks:
      - my_network

  gpt:
    build:
      context: .
      dockerfile: GPT/Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./GPT:/app
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
